/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorymanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PlaceOrderGUI extends javax.swing.JFrame {
    private Order order;// Composition: ChangeOrderDetailsGUI has Order
    /**
     * Creates new form PlaceOrderGUI
     */
    public PlaceOrderGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        productLbl = new javax.swing.JLabel();
        productTxtFld = new javax.swing.JTextField();
        quantityLbl = new javax.swing.JLabel();
        quantityTxtFld = new javax.swing.JTextField();
        priceLbl = new javax.swing.JLabel();
        priceTxtFld = new javax.swing.JTextField();
        supplierNameLbl = new javax.swing.JLabel();
        supplierNameTxtFld = new javax.swing.JTextField();
        deliveryDateLbl = new javax.swing.JLabel();
        deliveryDateTxtFld = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePanel.setBackground(new java.awt.Color(2, 50, 70));

        titleLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Place Order");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleLabel)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        productLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productLbl.setText("Product:");

        productTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTxtFldActionPerformed(evt);
            }
        });

        quantityLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quantityLbl.setText("Quantity:");

        quantityTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtFldActionPerformed(evt);
            }
        });

        priceLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        priceLbl.setText("Price:");

        supplierNameLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        supplierNameLbl.setText("Supplier Name:");

        supplierNameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierNameTxtFldActionPerformed(evt);
            }
        });

        deliveryDateLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deliveryDateLbl.setText("Delivery Date:");

        submitBtn.setBackground(new java.awt.Color(40, 112, 148));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(242, 242, 242));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(40, 112, 148));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(242, 242, 242));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(quantityLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(priceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(productLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(supplierNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(deliveryDateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(supplierNameTxtFld, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(priceTxtFld, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(quantityTxtFld, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(productTxtFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deliveryDateTxtFld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn)
                .addGap(239, 239, 239))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productLbl)
                    .addComponent(productTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLbl)
                    .addComponent(quantityTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLbl)
                    .addComponent(priceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierNameLbl)
                    .addComponent(supplierNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryDateLbl)
                    .addComponent(deliveryDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productTxtFldActionPerformed

    private void quantityTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtFldActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        Supplier supplier = null;
        String supplierName = supplierNameTxtFld.getText();
        if (supplierName.equalsIgnoreCase("AINUL MARDHIAH")) {
            supplier = new Supplier("AINUL MARDHIAH", "ainul@gmail.com", "RC1");
        } 
        else if (supplierName.equalsIgnoreCase("LEE YONG YI")) {
            supplier = new Supplier("LEE YONG YI", "lee@gmail.com", "RC2");
        } 
        else if (supplierName.equalsIgnoreCase("AIDA NADHIRAH")) {
            supplier = new Supplier("AIDA NADHIRAH", "aida@gmail.com", "RC3");
        } 
        else if (supplierName.equalsIgnoreCase("SYAMIMI")) {
            supplier = new Supplier("SYAMIMI", "im@gmail.com", "RC4");
        } 
        else {
            JOptionPane.showMessageDialog(rootPane, "Supplier not found.");
            return;
        }
        
        order = new Order(productTxtFld.getText(), 
                      Integer.parseInt(quantityTxtFld.getText()), 
                      supplier, 
                      Double.parseDouble(priceTxtFld.getText()), 
                      deliveryDateTxtFld.getText(), 
                      "Pending");
        
        addToList(order);
        clearTextField();
        order.displayDetails();
        
        this.setVisible(false);
        new MainPageGUI().setVisible(true);
    }//GEN-LAST:event_submitBtnActionPerformed

    private void supplierNameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierNameTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierNameTxtFldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Order placement is cancelled.");
        this.setVisible(false);
        new MainPageGUI().setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceOrderGUI().setVisible(true);
            }
        });
    }

    public void addToList(Order order) {
        for (int i = 0; i < order.getOrderList().length; i++) {
            if (order.getOrderList()[i] == null) {
                order.getOrderList()[i] = order;
                JOptionPane.showMessageDialog (rootPane, "Order added successfully.");
                return;
            }
        }
        JOptionPane.showMessageDialog (rootPane, "List is full. Unable to add the order.");
    }
    
    private void clearTextField() {
        productTxtFld.setText("");
        quantityTxtFld.setText("");
        priceTxtFld.setText("");
        supplierNameTxtFld.setText("");
        deliveryDateTxtFld.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel deliveryDateLbl;
    private javax.swing.JTextField deliveryDateTxtFld;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTxtFld;
    private javax.swing.JLabel productLbl;
    private javax.swing.JTextField productTxtFld;
    private javax.swing.JLabel quantityLbl;
    private javax.swing.JTextField quantityTxtFld;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel supplierNameLbl;
    private javax.swing.JTextField supplierNameTxtFld;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
