/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorymanagementsystem;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author user
 */
public class RaiseInvoiceGUI extends javax.swing.JFrame {
    // Encapsulation
    private Invoice invoice;// Composition: PaySupplierGUI has Invoice
    private String[] orderNames = new String[10];
    /**
     * Creates new form RaiseInvoiceGUI
     */
    public RaiseInvoiceGUI() {
        initComponents();
        populateOrderList();
        setupOrderListSelectionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        orderListLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList<>();
        outputPanel = new javax.swing.JPanel();
        orderDetailsLbl = new javax.swing.JLabel();
        orderIdLbl = new javax.swing.JLabel();
        orderIdTxtFld = new javax.swing.JTextField();
        productLbl = new javax.swing.JLabel();
        productTxtFld = new javax.swing.JTextField();
        quantityLbl = new javax.swing.JLabel();
        quantityTxtFld = new javax.swing.JTextField();
        priceLbl = new javax.swing.JLabel();
        priceTxtFld = new javax.swing.JTextField();
        supplierLbl = new javax.swing.JLabel();
        supplierTxtFld = new javax.swing.JTextField();
        deliveryDateLbl = new javax.swing.JLabel();
        deliveryDateTxtFld = new javax.swing.JTextField();
        statusLbl = new javax.swing.JLabel();
        statusTxtFld = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        invoiceDateLbl = new javax.swing.JLabel();
        invoiceDateTxtFld = new javax.swing.JTextField();
        paymentMethodLbl = new javax.swing.JLabel();
        paymentMethodTxtFld = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePanel.setBackground(new java.awt.Color(2, 50, 70));

        titleLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Raise Invoice");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(35, 35, 35))
        );

        bodyPanel.setBackground(new java.awt.Color(40, 112, 148));

        orderListLbl.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        orderListLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderListLbl.setText("Order List");

        jScrollPane1.setViewportView(orderList);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(orderListLbl))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(orderListLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderDetailsLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderDetailsLbl.setText("Order Details");

        orderIdLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        orderIdLbl.setText("Order ID: ");

        orderIdTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdTxtFldActionPerformed(evt);
            }
        });

        productLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productLbl.setText("Product:");

        productTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productTxtFldActionPerformed(evt);
            }
        });

        quantityLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quantityLbl.setText("Quantity:");

        quantityTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtFldActionPerformed(evt);
            }
        });

        priceLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        priceLbl.setText("Price:");

        supplierLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        supplierLbl.setText("Supplier:");

        supplierTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierTxtFldActionPerformed(evt);
            }
        });

        deliveryDateLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deliveryDateLbl.setText("Delivery Date:");

        statusLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        statusLbl.setText("Status:");

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(orderDetailsLbl)
                        .addGap(337, 337, 337))
                    .addGroup(outputPanelLayout.createSequentialGroup()
                        .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(outputPanelLayout.createSequentialGroup()
                                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orderIdLbl)
                                    .addComponent(productLbl)
                                    .addComponent(quantityLbl)
                                    .addComponent(priceLbl)
                                    .addComponent(supplierLbl)
                                    .addComponent(deliveryDateLbl))
                                .addGap(34, 34, 34)
                                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplierTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deliveryDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantityTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(orderIdTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(outputPanelLayout.createSequentialGroup()
                                .addComponent(statusLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(statusTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(184, 184, 184))))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orderDetailsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderIdLbl)
                    .addComponent(orderIdTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productLbl)
                    .addComponent(productTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLbl)
                    .addComponent(quantityTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLbl)
                    .addComponent(priceTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierLbl)
                    .addComponent(supplierTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryDateLbl)
                    .addComponent(deliveryDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLbl)
                    .addComponent(statusTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        invoiceDateLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        invoiceDateLbl.setText("Invoice Date:");

        paymentMethodLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paymentMethodLbl.setText("Payment Method:");

        paymentMethodTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentMethodTxtFldActionPerformed(evt);
            }
        });

        submitBtn.setBackground(new java.awt.Color(40, 112, 148));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(242, 242, 242));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(40, 112, 148));
        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(242, 242, 242));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paymentMethodLbl)
                            .addComponent(invoiceDateLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(invoiceDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentMethodTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(invoiceDateLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentMethodTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentMethodLbl)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(invoiceDateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(submitBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productTxtFldActionPerformed

    private void quantityTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtFldActionPerformed

    private void supplierTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierTxtFldActionPerformed

    private void orderIdTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderIdTxtFldActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Invoice generation is cancelled.");
        this.setVisible(false);
        new MainPageGUI().setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void paymentMethodTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentMethodTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentMethodTxtFldActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        int selectedIndex = orderList.getSelectedIndex();
        if (selectedIndex == -1 || Order.getOrderList()[selectedIndex] == null) {
            JOptionPane.showMessageDialog(rootPane, "Please select an order.");
            return;
        }
        Order selectedOrder = Order.getOrderList()[selectedIndex];
        
        String invoiceDate = invoiceDateTxtFld.getText();
        String paymentMethod = paymentMethodTxtFld.getText();
        
        double amountPayment = selectedOrder.getPrice() * selectedOrder.getQuantity();
        Payment payment = new Payment(invoiceDate, amountPayment, paymentMethod);
        invoice = new Invoice(selectedOrder.getProduct(), 
                selectedOrder.getQuantity(),
                selectedOrder.getSupplier(), 
                selectedOrder.getPrice(), 
                selectedOrder.getDeliveryDate(),
                selectedOrder.getStatus(), 
                invoiceDate,payment);
        
        addToList(invoice);
        clearTextField();
        invoice.displayDetails();
        
        this.setVisible(false);
        new MainPageGUI().setVisible(true);
    }//GEN-LAST:event_submitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaiseInvoiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaiseInvoiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaiseInvoiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaiseInvoiceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaiseInvoiceGUI().setVisible(true);
            }
        });
    }

    private void populateOrderList() {
        Order[] orders = Order.getOrderList();
        if (orders != null) {
            for (int i = 0; i < orders.length; i++) {
                if (orders[i] != null) {
                    orderNames[i] = orders[i].getProduct();
                }
            }
            orderList.setListData(orderNames);
        }
    }
    
    private void setupOrderListSelectionListener() {
        orderList.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedIndex = orderList.getSelectedIndex();
                    if (selectedIndex != -1) {
                        Order selectedOrder = Order.getOrderList()[selectedIndex];
                        if (selectedOrder != null) {
                            displayDetails(selectedOrder);
                        }
                    }
                }
            }
        });
    }

    private void displayDetails(Order order) {
        orderIdTxtFld.setText(String.valueOf(order.getOrderId()));
        productTxtFld.setText(order.getProduct());
        quantityTxtFld.setText(String.valueOf(order.getQuantity()));
        priceTxtFld.setText(String.valueOf(order.getPrice()));
        supplierTxtFld.setText(order.getSupplier().getName());
        deliveryDateTxtFld.setText(order.getDeliveryDate());
        statusTxtFld.setText("Pending");
    }
    
    public void addToList(Invoice invoice) {
        for (int i = 0; i < invoice.getInvoiceList().length; i++) {
            if (invoice.getInvoiceList()[i] == null) {
                invoice.getInvoiceList()[i] = invoice;
                JOptionPane.showMessageDialog(rootPane, "Invoice added successfully.");
                return;
            }
        }
        JOptionPane.showMessageDialog (rootPane, "List is full. Unable to add the order.");
    }

    private void clearTextField() {
        orderIdTxtFld.setText("");
        productTxtFld.setText("");
        quantityTxtFld.setText("");
        priceTxtFld.setText("");
        supplierTxtFld.setText("");
        deliveryDateTxtFld.setText("");
        statusTxtFld.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel deliveryDateLbl;
    private javax.swing.JTextField deliveryDateTxtFld;
    private javax.swing.JLabel invoiceDateLbl;
    private javax.swing.JTextField invoiceDateTxtFld;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderDetailsLbl;
    private javax.swing.JLabel orderIdLbl;
    private javax.swing.JTextField orderIdTxtFld;
    private javax.swing.JList<String> orderList;
    private javax.swing.JLabel orderListLbl;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JLabel paymentMethodLbl;
    private javax.swing.JTextField paymentMethodTxtFld;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTxtFld;
    private javax.swing.JLabel productLbl;
    private javax.swing.JTextField productTxtFld;
    private javax.swing.JLabel quantityLbl;
    private javax.swing.JTextField quantityTxtFld;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JTextField statusTxtFld;
    private javax.swing.JButton submitBtn;
    private javax.swing.JLabel supplierLbl;
    private javax.swing.JTextField supplierTxtFld;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
