/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorymanagementsystem;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author user
 */
public class ViewOrderGUI extends javax.swing.JFrame {
    // Encapsulation
    private Order order;// Composition: ChangeOrderDetailsGUI has Order
    private String[] orderNames = new String[10];
    /**
     * Creates new form ViewOrderGUI
     */
    public ViewOrderGUI() {
        initComponents();
        populateOrderList();// Association with Order class
        setupOrderListSelectionListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        ViewOrderLabel = new javax.swing.JLabel();
        CancelBtn = new javax.swing.JButton();
        SubmitBtn = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        orderListLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderList = new javax.swing.JList<>();
        OrderIDLabel = new javax.swing.JLabel();
        ProductLabel = new javax.swing.JLabel();
        QtyLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        SupplierLabel = new javax.swing.JLabel();
        DdateLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        ProductTxt = new javax.swing.JTextField();
        OrderIDTxt = new javax.swing.JTextField();
        QtyTxt = new javax.swing.JTextField();
        SupplierTxt = new javax.swing.JTextField();
        PriceTxt = new javax.swing.JTextField();
        DDateTxt = new javax.swing.JTextField();
        StatusTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePanel.setBackground(new java.awt.Color(2, 50, 70));
        titlePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ViewOrderLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        ViewOrderLabel.setForeground(new java.awt.Color(255, 255, 255));
        ViewOrderLabel.setText("View Order");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(ViewOrderLabel)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(ViewOrderLabel)
                .addGap(34, 34, 34))
        );

        CancelBtn.setBackground(new java.awt.Color(40, 112, 148));
        CancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        SubmitBtn.setBackground(new java.awt.Color(40, 112, 148));
        SubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        bodyPanel.setBackground(new java.awt.Color(40, 112, 148));

        orderListLbl.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        orderListLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderListLbl.setText("Order List");

        jScrollPane1.setViewportView(orderList);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(orderListLbl))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(orderListLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OrderIDLabel.setText("Order ID:");

        ProductLabel.setText("Product:");

        QtyLabel.setText("Quantity:");

        PriceLabel.setText("Price:");

        SupplierLabel.setText("Supplier:");

        DdateLabel.setText("Delivery Date:");

        StatusLabel.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(SubmitBtn)
                        .addGap(18, 18, 18)
                        .addComponent(CancelBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(StatusLabel)
                            .addGap(58, 58, 58)
                            .addComponent(StatusTxt))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(OrderIDLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ProductLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(QtyLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SupplierLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PriceLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SupplierTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(QtyTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ProductTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(OrderIDTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(DdateLabel)
                            .addGap(17, 17, 17)
                            .addComponent(DDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OrderIDLabel)
                            .addComponent(OrderIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductLabel)
                            .addComponent(ProductTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QtyLabel)
                            .addComponent(QtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SupplierLabel)
                            .addComponent(SupplierTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PriceLabel)
                            .addComponent(PriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DdateLabel)
                            .addComponent(DDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusLabel)
                            .addComponent(StatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmitBtn)
                            .addComponent(CancelBtn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        JOptionPane.showMessageDialog(rootPane, "View order is cancelled.");
        this.setVisible(false);
        new MainPageGUI().setVisible(true);
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        if (order == null) {
            JOptionPane.showMessageDialog(rootPane, "Please select an order from the list.");
            return;
        }

        String newProductName = ProductTxt.getText();
        int newQuantity = Integer.parseInt(QtyTxt.getText());
        double newPrice = Double.parseDouble(PriceTxt.getText());
        String newDeliveryDate = DDateTxt.getText();

        order.setProduct(newProductName);
        order.setQuantity(newQuantity);
        order.setPrice(newPrice);
        order.setDeliveryDate(newDeliveryDate);

        JOptionPane.showMessageDialog(rootPane, "View order successfully.");

        clearTextField();
        this.setVisible(false);
        new MainPageGUI().setVisible(true);
    }//GEN-LAST:event_SubmitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrderGUI().setVisible(true);
            }
        });
    }
    
    private void populateOrderList() {
        Order[] orders = Order.getOrderList();
        if (orders != null) {
            for (int i = 0; i < orders.length; i++) {
                if (orders[i] != null) {
                    orderNames[i] = orders[i].getProduct();
                }
            }
            orderList.setListData(orderNames);
        }
    }
    
    private void setupOrderListSelectionListener() {
        orderList.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedIndex = orderList.getSelectedIndex();
                    if (selectedIndex != -1) {
                        Order selectedOrder = Order.getOrderList()[selectedIndex];
                        if (selectedOrder != null) {
                            displayDetails(selectedOrder);
                        }
                    }
                }
            }
        });
    }
    
    private void displayDetails(Order order) {
        this.order = order;
        OrderIDTxt.setText(String.valueOf(order.getOrderId()));
        ProductTxt.setText(order.getProduct());
        QtyTxt.setText(String.valueOf(order.getQuantity()));
        PriceTxt.setText(String.valueOf(order.getPrice()));
        SupplierTxt.setText(order.getSupplier().getName());
        DDateTxt.setText(order.getDeliveryDate());
        StatusTxt.setText(order.getStatus());
    }

    private void clearTextField() {
        OrderIDTxt.setText("");
        ProductTxt.setText("");
        QtyTxt.setText("");
        PriceTxt.setText("");
        SupplierTxt.setText("");
        DDateTxt.setText("");
        StatusTxt.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField DDateTxt;
    private javax.swing.JLabel DdateLabel;
    private javax.swing.JLabel OrderIDLabel;
    private javax.swing.JTextField OrderIDTxt;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JLabel ProductLabel;
    private javax.swing.JTextField ProductTxt;
    private javax.swing.JLabel QtyLabel;
    private javax.swing.JTextField QtyTxt;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JTextField StatusTxt;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel SupplierLabel;
    private javax.swing.JTextField SupplierTxt;
    private javax.swing.JLabel ViewOrderLabel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> orderList;
    private javax.swing.JLabel orderListLbl;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
