/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventorymanagementsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class ViewInvoiceReportGUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewInvoiceReport
     */
    public ViewInvoiceReportGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoiceReportPanel = new javax.swing.JPanel();
        invoiceReportLbl = new javax.swing.JLabel();
        invoiceReportPanel1 = new javax.swing.JPanel();
        invoiceReportDataLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        invoiceReportTable = new javax.swing.JTable();
        submitBtn = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        invoiceReportPanel.setBackground(new java.awt.Color(2, 50, 70));

        invoiceReportLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        invoiceReportLbl.setForeground(new java.awt.Color(255, 255, 255));
        invoiceReportLbl.setText("Invoice Report");

        javax.swing.GroupLayout invoiceReportPanelLayout = new javax.swing.GroupLayout(invoiceReportPanel);
        invoiceReportPanel.setLayout(invoiceReportPanelLayout);
        invoiceReportPanelLayout.setHorizontalGroup(
            invoiceReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceReportPanelLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(invoiceReportLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        invoiceReportPanelLayout.setVerticalGroup(
            invoiceReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceReportPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(invoiceReportLbl)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        invoiceReportDataLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        invoiceReportDataLbl.setText("Invoice Report Data");

        invoiceReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Invoice Number", "Date", "Quantity", "Price", "Status", "Payment Method"
            }
        ));
        invoiceReportTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                invoiceReportTableInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(invoiceReportTable);

        submitBtn.setBackground(new java.awt.Color(40, 112, 148));
        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout invoiceReportPanel1Layout = new javax.swing.GroupLayout(invoiceReportPanel1);
        invoiceReportPanel1.setLayout(invoiceReportPanel1Layout);
        invoiceReportPanel1Layout.setHorizontalGroup(
            invoiceReportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceReportPanel1Layout.createSequentialGroup()
                .addGroup(invoiceReportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceReportPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
                    .addGroup(invoiceReportPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(invoiceReportDataLbl)
                        .addGap(0, 252, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceReportPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submitBtn)
                .addGap(281, 281, 281))
        );
        invoiceReportPanel1Layout.setVerticalGroup(
            invoiceReportPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoiceReportPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoiceReportDataLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBtn)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(invoiceReportPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(invoiceReportPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoiceReportPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invoiceReportPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        this.setVisible(false);
        new MainPageGUI().setVisible(true);
    }//GEN-LAST:event_submitBtnActionPerformed

    private void invoiceReportTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_invoiceReportTableInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceReportTableInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInvoiceReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInvoiceReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInvoiceReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInvoiceReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInvoiceReportGUI().setVisible(true);
            }
        });
    }
    
    public void displayPaidInvoice(String invoiceNumber, String date, String quantity, double price, String status, String paymentMethod) {
        DefaultTableModel model = (DefaultTableModel) invoiceReportTable.getModel();
        model.insertRow(0, new Object[] {invoiceNumber, date, quantity, price, status, paymentMethod});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel invoiceReportDataLbl;
    private javax.swing.JLabel invoiceReportLbl;
    private javax.swing.JPanel invoiceReportPanel;
    private javax.swing.JPanel invoiceReportPanel1;
    private javax.swing.JTable invoiceReportTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
